name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 2.3.0'

    - name: Build the web app
      run: |
        npm install
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3   # Updated to a valid version
      with:
        name: build-artifacts
        path: |
          build/
