name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install React Native CLI
        run: npm install -g react-native-cli

      - name: Install Dependencies
        run: npm install

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.1
        with:
          name: apk
          path: android/app/build/outputs/apk/release/*.apk

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: apk # Name of the artifact to download
          path: ./downloaded-artifacts # Destination path
          # Optional parameters can be added here if needed
          # pattern: # optional
          # merge-multiple: # optional, default is false
          # github-token: # optional
          # repository: # optional, default is ${{ github.repository }}
          # run-id: # optional, default is ${{ github.run_id }}