name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the appropriate Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run APK generation script
      run: node MyNewProject/index.js "${{ secrets.WEB_URL }}" "${{ secrets.ICON_PATH }}"
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.14-7/x64

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: MyNewProject/src/app-release.apk

    - name: Upload APK to WordPress
      uses: sebastianpopp/ftp-action@v1.0.0
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: MyNewProject/src
        remoteDir: /https://mofoluwakeedgar.com/apkdownload
