name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'node: 22.3.0'  # Use the appropriate Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run APK generation script
      run: node MyNewProject/index.js "https://example.com" "path/to/icon.png"
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.14-7/x64

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: MyNewProject/AppBuilder/android/app/build/outputs/apk/release/app-release.apk
